# MongoDB configuration file for Shard 2

# Storage Engine Options
storage:
  dbPath: /data/db

# Network settings
net:
  port: 27017
  bindIp: 0.0.0.0

# Process Management Options
processManagement:
  fork: false

# Logging Options
systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true

# Sharding Options
sharding:
  clusterRole: shardsvr

# Replica Set Options
replication:
  replSetName: rs-shard-02