# MongoDB configuration file for Shard 1 with Search Support

# Storage Engine Options
storage:
  dbPath: /data/db

# Network settings
net:
  port: 27017
  bindIp: 0.0.0.0

# Logging Options
systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true

# Sharding Options
sharding:
  clusterRole: shardsvr

# Replica Set Options
replication:
  replSetName: rs-shard-01

# Search configuration parameters
setParameter:
   # Server parameters to advise mongod of mongot availability for search index management and querying
   searchIndexManagementHostAndPort: mongot-shard01:27028
   mongotHost: mongot-shard01:27028
   skipAuthenticationToSearchIndexManagementServer: false
   useGrpcForSearch: true