# MongoDB configuration file for Mongos Router

# Network settings
net:
  port: 27017
  bindIp: 0.0.0.0

# Process Management Options
processManagement:
  fork: false

# Logging Options
systemLog:
  destination: file
  path: /data/db/mongod.log
  logAppend: true

# Sharding Options
sharding:
  configDB: rs-config-server/mongo-config-01:27017,mongo-config-02:27017,mongo-config-03:27017